# Generated by Django 4.2 on 2023-04-12 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование курса')),
                ('date_started', models.DateField(default=datetime.date.today, verbose_name='Дата начала курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Язык программирования')),
                ('month_to_learn', models.IntegerField(verbose_name='Продолжительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО человека')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='номер телефона')),
                ('work_study_place', models.CharField(blank=True, max_length=30, null=True, verbose_name='Место учебы/работы')),
                ('has_own_notebook', models.BooleanField(verbose_name='Есть ли свой ноутбук')),
                ('preferred_os', models.CharField(choices=[('windows', 'Windows'), ('macos', 'MacOS'), ('linux', 'Linux')], max_length=30, verbose_name='Предпочитаемая операционная система')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО человека')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='номер телефона')),
                ('main_work', models.CharField(blank=True, max_length=30, null=True, verbose_name='основное место работы ')),
                ('experience', models.DateField(verbose_name='дата начала работы программистом ')),
                ('courses', models.ManyToManyField(related_name='mentors', through='user.Course', to='user.student', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.language', verbose_name='Язык программирования'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mentor', verbose_name='Ментор'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Студент'),
        ),
    ]
